pipeline:
  Render Homepage:
    image: tenstartups/middleman
    commands:
      - cd homepage
      - bundle install
      - middleman build

  # Build Europe Blog:
  #   image: tomasbasham/ember:2.13.2
  #   commands:
  #     - cd eurotrip
  #     - npm install
  #     - ember build

  Render Hugo Tech Blog:
    image: jojomi/hugo:latest
    commands:
      - cd hugo_tech_blog
      - hugo

  Copy Assets to Folder:
    image: alpine
    commands:
      - rm -rf rendered_assets/*
      - cp -r homepage/build/* rendered_assets/
      - cp -r hugo_tech_blog/public rendered_assets/bits
      - cp -r old_map/deploy rendered_assets/map
      - cp -r eurotrip rendered_assets/euro

  Build Site Image:
    image: plugins/docker
    dockerfile: Dockerfile
    repo: corylogan/homepage
    tags:
      - latest
      - ${DRONE_COMMIT_SHA:8}

  Deploy To Kontena:
    image: kontena/cli
    commands:
      - SSL_IGNORE_ERRORS=true kontena stack deploy site
