pipeline:
  Render Homepage:
    image: tenstartups/middleman
    commands:
      - cd homepage
      - bundle install --quiet
      - middleman build

  Clone Europe Blog:
    image: indiehosters/git
    commands:
      - git clone https://github.com/counterbeing/europe-trip-blog.git

  Build Europe Blog:
    image: node:8.1.2
    commands:
      - cd europe-trip-blog
      - npm install -g ember-cli --silent
      - npm install --silent
      - ember build --environment="production"

  Render Hugo Tech Blog:
    image: jojomi/hugo:latest
    commands:
      - cd hugo_tech_blog
      - hugo

  Copy Assets to Folder:
    image: alpine
    commands:
      - rm -rf rendered_assets/*
      - cp -r homepage/build/* rendered_assets/
      - cp -r hugo_tech_blog/public rendered_assets/bits
      - cp -r old_map/deploy rendered_assets/map
      - cp -r eurotrip rendered_assets/euro
      - cp -r europe-trip-blog/dist rendered_assets/europe-trip-blog

  Build Site Image:
    image: plugins/docker
    dockerfile: Dockerfile
    repo: corylogan/homepage
    secrets: [ DOCKER_USERNAME, DOCKER_PASSWORD ]
    tags:
      - latest
      - ${DRONE_COMMIT_SHA:8}

  Deploy To Kontena:
    image: kontena/cli
    secrets: [ KONTENA_GRID, KONTENA_TOKEN, KONTENA_URL ]
    commands:
      - DEBUG=true SSL_IGNORE_ERRORS=true kontena stack deploy homepage
