pipeline:
  Render Hugo Tech Blog :
    image: jojomi/hugo:latest
    commands:
      - cd hugo_tech_blog
      - hugo

  Render Homepage:
    image: corylogan/middleman-docker:latest
    pull: true
    commands:
      - cd homepage
      - bundle install --quiet
      - middleman build

  Clone Blogs:
    image: indiehosters/git
    commands:
      - git clone https://github.com/counterbeing/europe-trip-blog.git
      - git clone https://github.com/counterbeing/south-america-blog.git

  Build Europe Blog:
    image: node:8.1.2
    commands:
      - cd europe-trip-blog
      # - npm install -g ember-cli@2.14.1 --silent
      # - npm install --silent
      - yarn global add ember-cli@2.14.1 --silent
      - yarn --silent
      - ember build --environment="production"

  Build South America Blog:
    image: node:6.11
    commands:
      - cd south-america-blog
      # - npm install -g ember-cli --silent
      - yarn global add ember-cli
      - yarn
      - ember build --prod


  Copy Assets to Folder:
    image: alpine
    commands:
      - cp -r homepage/build/* rendered_assets/
      - cp -r hugo_tech_blog/public rendered_assets/bits
      - cp -r europe-trip-blog/dist rendered_assets/eu
      - rm -rf europe-trip-blog
      - cp -r south-america-blog/dist rendered_assets/sa
      - rm -rf south-america-blog
      - cp -r static/* ./rendered_assets/

  Commit:
    image: indiehosters/git
    commands:
      - git config --global user.email "ci@drone.corylogan.com"
      - git config --global user.name "Drone Server"
      - git fetch origin
      - git checkout --track origin/gh-pages
      - cp -r rendered_assets/* ./ && rm -rf rendered_assets
      - echo 'ran' >> README.md
      - git add .
      - git commit -am "build $(date +'%Y/%m/%d %H:%M:%S:%3N')"

  Git Push:
    image: appleboy/drone-git-push
    environment:
      GIT_PUSH_SSH_KEY:
        from_secret: github_private_key
    remote: git@github.com:counterbeing/homepage.git
    force: false
    branch: gh-pages
    local_ref: gh-pages



  # Build Sitemap:
  #   image: node:8.1.2
  #   commands:
  #     - cd rendered_assets
  #     - yarn global add sitemap-static minimal-sitemap --silent
  #     # - npm install -g sitemap-static minimal-sitemap --silent
  #     - sitemap-static --prefix=https://www.corylogan.com > ./partial.xml
  #     - combine_sitemaps ./partial.xml ./sa/sitemap.xml > ./sitemap.xml
  #
  # Build Site Image:
  #   image: plugins/docker
  #   dockerfile: Dockerfile
  #   repo: corylogan/homepage
  #   secrets: [ DOCKER_USERNAME, DOCKER_PASSWORD ]
  #   tags:
  #     - latest
  #     - ${DRONE_COMMIT_SHA:8}
  # Submit sitemap to google:
  #   image: appropriate/curl
  #   commands:
  #     - curl http://google.com/ping?sitemap=https://www.corylogan.com/sitemap.xml
branches:
  - master
