kind: pipeline
name: default

steps:
  - name: Render Hugo Tech Blog
    image: jojomi/hugo:latest
    commands:
      - cd hugo_tech_blog
      - hugo

  # - name: Render Homepage
  #   image: corylogan/middleman-docker:latest
  #   pull: true
  #   commands:
  #     - cd homepage
  #     - bundle install --quiet
  #     - middleman build
  #
  # - name: Clone Blogs
  #   image: indiehosters/git
  #   commands:
  #     - git clone https://github.com/counterbeing/europe-trip-blog.git
  #     - git clone https://github.com/counterbeing/south-america-blog.git
  #
  # - name: Build Europe Blog
  #   image: node:8.1.2
  #   commands:
  #     - cd europe-trip-blog
  #     # - npm install -g ember-cli@2.14.1 --silent
  #     # - npm install --silent
  #     - yarn global add ember-cli@2.14.1 --silent
  #     - yarn --silent
  #     - ember build --environment="production"
  #
  # - name: Build South America Blog
  #   image: node:6.11
  #   commands:
  #     - cd south-america-blog
  #     # - npm install -g ember-cli --silent
  #     - yarn global add ember-cli
  #     - yarn
  #     - ember build --prod
  #
  #
  - name: Copy Assets to Folder
    image: alpine
    commands:
  #     - cp -r homepage/build/* rendered_assets/
      - cp -r hugo_tech_blog/public rendered_assets/bits
  #     - cp -r europe-trip-blog/dist rendered_assets/eu
      - rm -rf europe-trip-blog
  #     - cp -r south-america-blog/dist rendered_assets/sa
      - rm -rf south-america-blog
  #     - cp -r static/* ./rendered_assets/

  #
  - name: Commit
    image: indiehosters/git
    environment:
      SSH_PRIVATE_KEY:
        from_secret: github_private_key
    commands:
      - git remote set-url origin git@github.com:counterbeing/homepage.git
      - mkdir -p  /root/.ssh
      - echo "$SSH_PRIVATE_KEY" > /root/.ssh/id_ed25519
      - ssh-agent /bin/sh
      - ssh-add /root/.ssh/id_ed25519
      - git config --global user.email "ci@drone.corylogan.com"
      - git config --global user.name "Drone Server"
      - rm -rf src/south-america-blog
      - git fetch origin
      - git checkout --track origin/gh-pages
      - cp -r rendered_assets/* ./ && rm -rf rendered_assets
      - echo 'ran' >> README.md
      - git add .
      - git commit -am "build $(date +'%Y/%m/%d %H:%M:%S:%3N')"
      - git push origin HEAD

  # - name: publish
  #   image: plugins/gh-pages
  #   settings:
  #     username:
  #       from_secret: github_private_key
  #     password: x-oauth-basic
  #     pages_directory: rendered_assets

  # - name: Git Push
  #   image: appleboy/drone-git-push
  #   environment:
  #     USERNAME:
  #       GIT_PUSH_SSH_KEY: "github_private_key"
  #   settings:
  #     remote: git@github.com:counterbeing/homepage.git
  #     force: false
  #     branch: gh-pages
  #     local_ref: gh-pages



  # Build Sitemap:
  #   image: node:8.1.2
  #   commands:
  #     - cd rendered_assets
  #     - yarn global add sitemap-static minimal-sitemap --silent
  #     # - npm install -g sitemap-static minimal-sitemap --silent
  #     - sitemap-static --prefix=https://www.corylogan.com > ./partial.xml
  #     - combine_sitemaps ./partial.xml ./sa/sitemap.xml > ./sitemap.xml
  #
  # Build Site Image:
  #   image: plugins/docker
  #   dockerfile: Dockerfile
  #   repo: corylogan/homepage
  #   secrets: [ DOCKER_USERNAME, DOCKER_PASSWORD ]
  #   tags:
  #     - latest
  #     - ${DRONE_COMMIT_SHA:8}
  # Submit sitemap to google:
  #   image: appropriate/curl
  #   commands:
  #     - curl http://google.com/ping?sitemap=https://www.corylogan.com/sitemap.xml
branches:
  - master
