# theme.toml template for a Hugo theme
# See https://github.com/spf13/hugoThemes#themetoml for an example

baseurl = "https://www.corylogan.com/bits"
languageCode = "en-us"
title = "Bits and Blocks"
theme = "after-dark"
enableRobotsTXT = true
description = "A place for me to stick my tech related notes and thoughts."
homepage = "https://www.corylogan.com"
googleAnalytics = "UA-19114773-9"
min_version = 0.24
SectionPagesMenu = "main"
PygmentsCodeFences = true
pygmentsUseClasses = true # Required for custom syntax highlighting
[[menu.main]]
  name = "Home"
  weight = 5
  identifier = "home"
  url = "../"

[author]
  name = "Cory Logan"
  homepage = "https://www.corylogan.com"
  SectionPagesMenu = "main"

[params]
  powered_by = false
  author = "Cory Logan"
